### ISSUE TITLE
Wrong directory path when deployed in docker

### ISSUE THREAD

**Issue by FairyFox5700** [FairyFox5700/Time-Tracking#23]
12:22:04 ERR] An error occured while creating report
System.ArgumentException: Parameter must contain file extension. Use ExcelFile.Load method that accepts LoadOptions parameter if you don't want to specify file extension. (Parameter 'path')
   at GemBox.Spreadsheet.LoadOptions.FromPathExtension(String path)
   at TimeTracking.ReportGenerator.Bl.Impl.Services.ReportExporter.GenerateReportForExport(UserActivityDto userActivity, ReportFormatType formatType) in /src/src/ReportGenerator/TimeTracking.ReportGenerator.Bl.Impl/Services/ReportExporter.cs:line 36
System.ArgumentException: Parameter must contain file extension. Use ExcelFile.Load method that accepts LoadOptions parameter if you don't want to specify file extension. (Parameter 'path')
   at GemBox.Spreadsheet.LoadOptions.FromPathExtension(String path)
   at TimeTracking.ReportGenerator.Bl.Impl.Services.ReportExporter.GenerateReportForExport(UserActivityDto userActivity, ReportFormatType formatType) in /src/src/ReportGenerator/TimeTracking.ReportGenerator.Bl.Impl/Services/ReportExporter.cs:line 36

**Comment by FairyFox5700** [comment]
fixed with PR https://github.com/FairyFox5700/Time-Tracking/pull/21
